global:
  scrape_interval: 5s
  scrape_timeout: 4s

server:
  verticalAutoscaler:
    enabled: false
  extraScrapeConfigs:
    - job_name: "muffin-wallet"
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: ["muffin-wallet.default.svc.cluster.local:80"]
