apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-wallet.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "muffin-wallet.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}